### ISSUE TITLE
PBE energies of GAMESS vs QP2

### ISSUE THREAD

**Issue by aannabe** [QuantumPackage/qp2#119]
Hello,
I think there might be something off in PBE implemented in QP2.
I have attached two runs that use GAMESS for SCF versus QP2 for SCF to do CIS/PBE.
One can see that both PBE energies, as well as CIS energies, differ for these two.
Both cases use the same ECP, basis, etc.

My QP2 version:
Git Date  : Tue Jun 16 18:00:02 2020 +0200
Git SHA1  : 470addca0292ec2f3c9935321a2d9da7c10de5f6

Thank you.

[gamess_vs_qp2.zip](https://github.com/QuantumPackage/qp2/files/4894697/gamess_vs_qp2.zip)

**Comment by scemama** [comment]
Hi,
have you tried with another software to check that the Gamess result is correct?

**Comment by scemama** [comment]
If you do the CIS using PBE orbitals, and if the PBE calculations differ between the 2 codes, you will get different MOs and it is normal that the CIS/PBE energies differ.
Are the Hartree-Fock energies compatible between the 2 codes?

**Comment by aannabe** [comment]
> Hi,
> have you tried with another software to check that the Gamess result is correct?

GAMESS: -6.2568293956 Ha
PySCF    : -6.2568777711 Ha
QP2:       : -6.2510636245 Ha


> If you do the CIS using PBE orbitals, and if the PBE calculations differ between the 2 codes, you will get different MOs and it is normal that the CIS/PBE energies differ.
> Are the Hartree-Fock energies compatible between the 2 codes?

Agreed, I tried CIS/PBE to see if the energy discrepancy between PBE was just an arbitrary shift. But apparently MOs are different. I don't have QP HF energy at the moment (Molpro gives: -6.08674468 Ha) but I don't recall seeing any discrepancies from other runs.

Thank you for looking at this.
Gani.

**Comment by scemama** [comment]
Hi,
I found the problem: The basis set for Si is different between your two calculations. If you run the PBE calculation starting from the GAMESS converted directory, you get:
-6.2570735 with grid_type = 2  (default)  and 
-6.2568561 with grid_type = 3
 So the PBE is OK

**Comment by aannabe** [comment]
Not sure how I missed that. Good to know PBE is fine. Thanks for looking again!
