### ISSUE TITLE
Makefile contents

### ISSUE THREAD

**Issue by abigcoder04** [QuantumPackage/qp2#212]
hello，my bro：
./configure -c ./config/gfortran_avx.cfg
After the configuration, the contents of the Makefile remain the same：
default: build.ninja
	bash -c "source quantum_package.rc ; ninja"

build.ninja:
	@bash -c ' echo '' ; echo xxxxxxxxxxxxxxxxxx ; echo "The QP is not configured yet. Please run the ./configure command" ; echo xxxxxxxxxxxxxxxxxx ; echo ''  ; ./configure --help' | more

Is this normal？I need to modify the contents in the Makefile, so I hope to get your answer.

**Comment by scemama** [comment]
Yes it is normal. QP is compiled with ninja, so make calls ninja.

**Comment by abigcoder04** [comment]
@scemama 
my bro, If I want to change the statements inside the compiled file, to change some statements that the compiler executes by default, which file should I change?

**Comment by scemama** [comment]
The compiler flags are specified in the files in the `config` directory. If you need to change compiler flags, you should create your own new file, otherwise it will be overwritten when you make a git pull.
 
These configuration files are parsed by scripts to produce the `config/build.ninja` file which is used by ninja to compile the files.
The scripts producing the `config/build.ninja` file are located in `scripts/compilation/`.

**Comment by abigcoder04** [comment]
If I now install QP under another version of Linux kernel, such as ARM, I have the following error in the make process：

bash -c "source quantum_package.rc ; ninja"
[WARNING] Running as root is not recommended
[1/3] Compiling all modules
[0/138] Create /root/test/qp2/lib/libezfio_irp.a
make[1]: Entering directory '/root/test/qp2/external/ezfio'
make -C src veryclean
make[2]: Entering directory '/root/test/qp2/external/ezfio/src'
mkdir -p IRPF90_temp/
gfortran -ffree-line-length-none -I . -mavx -g -fPIC -fopenmp -c system_f.f90 -o IRPF90_temp/system_f.o && cp system.mod IRPF90_temp/
gfortran: error: unrecognized command line option ‘-mavx’

Now I need to modify the Makefile followed by QP compilation, but since QP is compiled by calling ninja, I need to modify which file to modify：
gfortran: error: unrecognized command line option ‘-mavx’

**Comment by scemama** [comment]
You need to create a new config file where the flag `-mavx` is absent. But I believe you will have other problems on ARM because we never tested it.
