### ISSUE TITLE
Test case script

### ISSUE THREAD

**Issue by abigcoder04** [QuantumPackage/qp2#214]
|>
[root@host-10-208-55-132 qp2]# vi test.sh
|>
[root@host-10-208-55-132 qp2]# bash test.sh
test.sh: line 4: qp: command not found
test.sh: line 5: qp: command not found
test.sh: line 6: qp: command not found
|>
[root@host-10-208-55-132 qp2]# qp
qp - Shell function of the qpsh shell

Why can I execute the qp statement directly on the command line, but if I put the qp statement inside the script and let the script execute it, it will show that the qp operation cannot be found

**Comment by scemama** [comment]
`qp` is a shell command introduced in your current shell when you `source /path/to/qp2/quantum_package.rc`. When you run `test.sh`, you execute a new bash to run your script, and the `qp` function is not inherited in this new shell.
You should add  `source /path/to/qp2/quantum_package.rc` to your test script for it to know the `qp` command, or you can execute your script in the same shell: `source script.sh`
