### ISSUE TITLE
ocaml 4.11 in qp2-dependencies incompatible with glibc>=2.34

### ISSUE THREAD

**Issue by kgasperich** [QuantumPackage/qp2#226]
Hi Anthony,

The ocaml-bundle in qp2-dependencies is v4.11, and it [won't build with glibc >=2.34](https://github.com/ocaml/ocaml/issues/10250).
This appears to be [fixed in 4.13](https://github.com/ocaml/ocaml/issues/10250#issuecomment-988077163), but I'm not sure whether all of the packages that qp2 depends on are present in 4.13/4.14.
It looks some [patches exist](https://github.com/ocaml/ocaml/issues/10250#issuecomment-1019899837) to be able to build ocaml v4.10+ with newer versions of glibc, but I think the process of adding that to the build process may be a similar amount of work to just switching from 4.11 to 4.13.

I haven't had much time to look into this, but can try to build qp2 with 4.13 and see if I run into any issues.

**Comment by scemama** [comment]
Hi Kevin,The packages that qp depend on are all OK with 4.13/4.14, but
I had to make a few corrections in the code. I made this changes in the
dev branch of QP, but they are not yet merged in the master. So if you
use the dev branch, it should work!
