### ISSUE TITLE
SCF energy

### ISSUE THREAD

**Issue by abigcoder04** [QuantumPackage/qp2#229]
Dear author,
    I want to ask about the expected energy result value after scf execution. I see that the expected value of SCF energy in the case given on your official website is only the first 9 decimal places. This is the expected value of SCF energy obtained in the actual test process. As long as the first 9 decimal places are fixed, can the following digits fluctuate. Hope to get your answer!

**Comment by scemama** [comment]
Hi,yes, then can fluctuate.
