### ISSUE TITLE
Ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by Chikakoyanagida** [QuantumPackage/qp2#299]
Hello, I have encountered this issue at the final stage of compilation:

ninja

[1/3] Compiling all modules

[135/200] Running IRPF90 for basis_correction

FAILED: /home/jasonyang/qp2/src/basis_correction/irpf90_entities /home/jasonyang/qp2/src/basis_correction/tags /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/build.ninja 

cd /home/jasonyang/qp2/src/basis_correction ; export FC='gfortran -ffree-line-length-none -I . -mavx -g -fPIC -fopenmp' ; export FCFLAGS='-Ofast -mavx' ; export LIB='-llapack -lblas /home/jasonyang/qp2/lib/libezfio_irp.a /home/jasonyang/qp2/lib/libf77zmq.a /home/jasonyang/qp2/lib/libzmq.a -lstdc++ -lrt -ldl  -lz  ' ; export SRC='/home/jasonyang/qp2/src/basis_correction/ao_one_e_ints/pseudopot.f90 /home/jasonyang/qp2/src/basis_correction/becke_numerical_grid/angular.f /home/jasonyang/qp2/src/basis_correction/bitmask/bitmasks_module.f90 /home/jasonyang/qp2/src/basis_correction/csf/cfgCI_interface.f90 /home/jasonyang/qp2/src/basis_correction/csf/cfgCI_utils.c /home/jasonyang/qp2/src/basis_correction/csf/tree_utils.c /home/jasonyang/qp2/src/basis_correction/utils/c_funcs.c /home/jasonyang/qp2/src/basis_correction/utils/c_functions.f90 /home/jasonyang/qp2/src/basis_correction/utils/fortran_mmap.c /home/jasonyang/qp2/src/basis_correction/utils/intel.f90 /home/jasonyang/qp2/src/basis_correction/utils/loc.f /home/jasonyang/qp2/src/basis_correction/utils/map_module.f90 /home/jasonyang/qp2/src/basis_correction/utils/mmap.f90 /home/jasonyang/qp2/src/basis_correction/utils/qsort.c /home/jasonyang/qp2/src/basis_correction/utils/qsort_module.f90 /home/jasonyang/qp2/src/basis_correction/zmq/f77_zmq_module.F90' ; export OBJ='/home/jasonyang/qp2/src/basis_correction/IRPF90_temp/ao_one_e_ints/pseudopot.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/becke_numerical_grid/angular.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/bitmask/bitmasks_module.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/csf/cfgCI_interface.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/csf/cfgCI_utils.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/csf/tree_utils.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/utils/c_funcs.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/utils/c_functions.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/utils/fortran_mmap.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/utils/intel.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/utils/loc.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/utils/map_module.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/utils/mmap.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/utils/qsort.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/utils/qsort_module.o /home/jasonyang/qp2/src/basis_correction/IRPF90_temp/zmq/f77_zmq_module.o' ; irpf90 -I ao_basis -I ao_one_e_ints -I ao_two_e_erf_ints -I ao_two_e_ints -I aux_quantities -I basis -I becke_numerical_grid -I bitmask -I cas_based_on_top -I csf -I davidson -I davidson_undressed -I density_for_dft -I determinants -I dft_keywords -I dft_one_e -I dft_utils_func -I dft_utils_in_r -I electrons -I ezfio_files -I functionals -I mo_basis -I mo_one_e_ints -I mo_two_e_erf_ints -I mo_two_e_ints -I mpi -I mu_of_r -I nuclei -I pseudo -I two_body_rdm -I two_rdm_routines -I utils -I zmq --ninja --align=32 -DSET_NESTED --openmp

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

/bin/sh: 1: python: not found

Error:

-----

Variable n_det_alpha_unique unknown 

file determinants/spindeterminants.irp.f ; line 378 :

   TOUCH psi_bilinear_matrix_values psi_bilinear_matrix_rows psi_bilinear_matrix_columns N_det_alpha_unique N_det_beta_unique psi_det_alpha_unique psi_det_beta_unique psi_bilinear_matrix_order

ninja: build stopped: subcommand failed.

FAILED: all 

ninja -f /home/jasonyang/qp2/config/build.ninja

ninja: build stopped: subcommand failed.

**Comment by djstaros** [comment]
Dear Chikakoyanagida,

First of all, it looks like you do not have Python in your $PATH. I would suggest you add this and try again.

Best regards,
Daniel Staros

**Comment by markdewing** [comment]
I ran into this issue on Ubuntu 22.04, where 'python3' is the only python executable installed by default.  It looks like most places in the QP2 source have been updated to use 'python3' instead of 'python' for the executable name, but there must be some places where the update was missed.
