### ISSUE TITLE
Issues Installing Quantum Package Using zsh Shell

### ISSUE THREAD

**Issue by djstaros** [QuantumPackage/qp2#312]
When attempting to install Quantum Package 2 following the install instructions at https://quantum-package.readthedocs.io/en/master/intro/install.html on a 2020 MacBook Pro (default shell zsh) running Ventura, I run into several issues which seem to ultimately be related to the shell environment. I am unable to figure out how to build Quantum Package 2 due to these issues.

This is what I have tried:
**Step 1:** `git clone https://github.com/QuantumPackage/qp2 (then cd into qp2)`
**Step 2:** `./configure -i all`        (NOTE: `./configure` on its own gave me issues about dependencies not being installed)
**Step 3:** `./configure -c config/gfortran.cfg`
**Step 4:** `source quantum_package.rc`
       --> **ERROR:** `quantum_package.rc:cd:22: no such file or directory: /Users/danielstaros/etc`
**Step 5:** Set `QP_ROOT="/Users/danielstaros/Codes/qp2"` within quantum_package.rc
**Step 6:** `source quantum_package.rc`
       --> **ERROR:** `quantum_package.rc:cd:22: no such file or directory: /Users/danielstaros/etc`
**Step 7:** `echo $(ps -p $$ -ocomm=)`
       --> **OUTPUT:** `-zsh`
**Step 8:** Change `"zsh"` in quantum_package.rc to `"-zsh"`
**Step 9:** `source quantum_package.rc`
       --> **ERRORS:** `configure.rc:34: command not found: complete`
       --> `qp.rc:301: command not found: complete`
**Step 10:** Add the following to my ~/.zshrc file and re-source ~/.zshrc (suggestion from [StackOverflow](https://superuser.com/questions/1714374/command-not-found-complete-message-appears-every-time-i-open-the-terminal)):
       --> `autoload -U +X bashcompinit && bashcompinit`
       --> `autoload -U +X compinit && compinit`
**Step 11:** `source quantum_package.rc`
       --> **NO ERROR!**
**Step 12:** `make`
       --> **ERRORS:** `ocamlfind: Package 'zmq' not found`
       --> `Command exited with code 2.`
       --> `Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.`
       --> `make[1]: *** [qptypes_generator.byte] Error 10`
       --> `FAILED: ocaml_target `
       --> `make -C /Users/danielstaros/Codes/qp2/ocaml`
       --> `ninja: build stopped: subcommand failed.`
       --> `make: *** [default] Error 1`

This looks like some issue regarding ocaml, but ocaml seemed to install correctly when I configured the dependencies in **Step 2**. I have not been able to troubleshoot this error, but even if I was, this example still makes it clear that installing Quantum Package 2 in a zsh shell on MacBook Pro is not particularly straightforward. I believe the user experience would definitely benefit from changes that address this issue, if possible. Any insight for how to fix this would be greatly appreciated!

Thank you,
Daniel Staros

**Comment by scemama** [comment]
Dear Daniel,
MacOS is not supported by QP, only Linux. We are working on it (in low priority), but there is still a lot to do.
best,
Anthony

**Comment by djstaros** [comment]
Dear Anthony,

Thank you for the prompt response. I see. I am looking forward to the support whenever it is launched :) Feel free to close this issue until then.

Kind regards,
Daniel
