### ISSUE TITLE
orbital optimization crash with memory issue.

### ISSUE THREAD

**Issue by anbenali** [QuantumPackage/qp2#319]
Cipsi-orb opt exits with crash and exit2 message after few cipsi iterations with "unable to dealocate map" 

The system is O2 and the basisset is cc-pvtz_ecp_ccecp

```
System 
  2

  O            0.00000000       0.00000000       0.00000000
  O            0.00000000       0.00000000       1.20750000
```

The exit file is attached but the error message is:

```

---rotation_matrix---
 Max error in R.R^T:  1.112980249084082E-014
 Time in rotation matrix:  7.240772247314453E-004
 ---End rotation_matrix---

 ---apply_mo_rotation---
 Time in apply mo rotation:  7.081031799316406E-004
 ---End apply_mo_rotation---
 Unable to deallocate map
Program exited with code 2.
Wall time: 0:00:05

```

[CIPSI.TXT](https://github.com/QuantumPackage/qp2/files/14223461/CIPSI.TXT)

**Comment by scemama** [comment]
This is probably due to the use of ifx. This does not happen with ifort and gfortran.

**Comment by anbenali** [comment]
Something has changed as I had to create a new ezfio then run the orb. Opt.
Now it works if I create a new ezfio and fresh optimization. Sorry for the
false alarm
