### ISSUE TITLE
reverse PR (fix Save_for_qmcpack) did not work? 

### ISSUE THREAD

**Issue by anbenali** [QuantumPackage/qp2#75]
Apparenttly the function save_wavefunction_qmcpack in src/determinant/determinant.irp.f was not reverted correctly and the function for saving for qmcpack is still there. I have moved that function to the plugin so now there is a conflict. 

Is it possible to revert it properly or should I put a PR?

**Comment by anbenali** [comment]
Did not see the PR #73

**Comment by scemama** [comment]
Yes, I forgot to merge it....
