### ISSUE TITLE
Problem with qp set_frozen_core

### ISSUE THREAD

**Issue by eginer** [QuantumPackage/qp2#96]
On branch dev here is the error when running qp set_frozen_core 

Traceback (most recent call last):
  File "/home/emmanuel/programs/qp2/bin/qp_set_frozen_core", line 56, in <module>
    from ezfio import ezfio
  File "/home/emmanuel/programs/qp2/external/ezfio/Python/ezfio.py", line 156
    print '------------------------------------------------------------'
                                                                       ^
SyntaxError: Missing parentheses in call to 'print'

Commit : be3aa1af71765a0b43dd775b8f2363a19a4c8759

**Comment by scemama** [comment]
This is related to your installation : you are using EZFIO 1.7 which is for Python2. You should be using EZFIO 2.0 which is for Python3.

You should restart from a fresh QP and reinstall everything.
